config/routes.rb
Rails.application.routes.draw do
 
  
    root 'users#home'

    resources :users

    get '/signup', to: "users#new"
    post '/signup', to: "users#create"
  
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
  
  
    get '/logout' => 'sessions#destroy'
    

    resources :users, only: [:show] do 
    resources :reviews, only: [:index, :show, :new, :edit] 
  end

  resources :reviews

  resources :restaurants, except: [:new, :create, :edit, :update, :destroy]

  resources :restaurants, only: [:show, :index] do
    resources :reviews, only: [:show, :index]
  end
  get '/reviews/:id/review_data', to: 'reviews#review_data'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :restaurants, through: :reviews, dependent: :destroy

  before_save { self.email = email.downcase } 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.alphabetical_order 
    User.order(email: :asc)
  end

  def self.authenticate(email, submitted_password) 
    user = find_by_email(email)
    return user.nil? ? nil : user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:home, :new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def home
  end

  def index
    @users = User.all.alphabetical_order.page(params[:page]).per(20)
  end

  def show
    @reviews = @user.reviews
    
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to '/', success: "Signup successful!"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User successfully updated!"
    else
      render :edit
    end
  end

  def destroy
      @user.destroy
      redirect_to '/', notice: "User successfully deleted!"
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email,
                                   :password,
                                   :password_confirmation)
    end

    def correct_user 
      @user = User.find(params[:id])
      redirect_to user_path(current_user),
      alert: "Sorry NO access to that page!" unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
   <% if @user.errors.any? %>
    <div id="error_explanation">
     <ol style="color:red;font-size:20px;font-style:italic;">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </ol>
    </div>
  <% end %>
  <br/>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br></br>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br></br>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>
  <br></br>
</div>
  <%= f.submit "Save User" ,class: "btn btn-outline-primary"%>
  <% end %>

app/views/users/_links.html.erb
<%= link_to "All Reviews", reviews_path %>
<%= link_to "All Restaurants", restaurants_path %>
<% if logged_in? %>
<%= link_to "All Users", users_path %>
<% end %>

app/views/users/edit.html.erb
<fieldset>
<legend>
  <h2>Update Login Email and/or Password</h2>
</legend>
<%= render 'form' %>
</fieldset>
  <br/>
  <fieldset>
    <legend>
      <h3>Delete Profile</h3>
    </legend>
  <br/>
  <%= button_to 'Delete User', user_path(@user),
              method: :delete,
              data: { confirm: 'This will delete your User profile & ALL your reviews! Continue?' } %>
  </fieldset>
</strong>
<br/>

app/views/users/home.html.erb
<h2>Welcome to My Restaurant Review!</h2>
<p>
  Here you can post reviews of your favorite (and not so favorite) restaurants.  Bon appetit!
  Online review websites are one of the best lead generation tools for restaurants. But only if your restaurant has plenty of great reviews.

Get listed as one of the highest-rated restaurants in your area and you can expect a flood of visitors. Suffer from a string of poor reviews and you can forget about having a full house.

Like ’em or hate ’em, restaurant review sites have become a major part of the restaurant industry. It is absolutely crucial for restaurateurs to be encouraging customers to review their restaurant and actively monitoring (and responding to) what customers have to say.
</p>
<% if logged_in? %>
<fieldset>
<legend>
  <p>
    Click on one of the following links below to:
  </p> <!--CRUDS-->
</legend>
<br/>
    <ul>
      <li><%= link_to "(C)reate your review", new_review_path %></li>
    </ul>
    <ul>
      <li><%= link_to "(R)ead your review", user_path(current_user) %></li>
    </ul>
    <ul>
      <li><%= link_to "(U)pdate your review", user_path(current_user) %></li>
    </ul>
    <ul>
      <li><%= link_to "(D)elete your review", user_path(current_user) %></li>
    </ul>
</fieldset>
<% end %>
<br/>

app/views/users/index.html.erb
<fieldset>
<legend>
  <h2>Users Directory</h2>
</legend>
<br/>
<ol>
  <li>
    <% if logged_in? %>
      <%= link_to "You", user_path(current_user) %>
      - Review Count:
    (<b><%= current_user.reviews.count %></b>)
    <% end %>
  </li>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email.upcase_first, user %>
      - Review Count:
      (<b><%= user.reviews.count %></b>)
    </li>
  <% end %>
</ol>
<%= page_entries_info @users %>
<%= paginate @users %>
</fieldset>
<br/>

app/views/users/new.html.erb
<fieldset>
<legend>
  <h2>Sign Up</h2>
</legend>
<%= render 'form' %>
</fieldset>
<br/>

app/views/users/show.html.erb
<fieldset>

  <h2>User Page</h2>

<br/>
<ul>
  <li><b>User Email:</b>&ensp;
    <%= @user.email %>
  </li>
  <br/>
  <% if @user.reviews.any? %>
  <li>
    <b>Total Reviews Submitted:</b>&ensp;
    (<%= @user.reviews.count %>)
  </li>
  </br>
  <ol>
    <%= render @reviews %>
  </ol>
  <% end %>
  <% if current_user == @user %>
  <li>
    <%= link_to "Submit New Review", new_user_review_path(@user) %>
  </li>
  <br/>
  <li><b>Change User Settings:</b>&ensp;
    <%= link_to "Edit User", edit_user_path %>
  </li>
  <% end %>
</ul>
</fieldset>
<br/>