config/routes.rb
Rails.application.routes.draw do
 
  
    root 'users#home'

    resources :users

    get '/signup', to: "users#new"
    post '/signup', to: "users#create"
  
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
  
  
    get '/logout' => 'sessions#destroy'
    

    resources :users, only: [:show] do 
    resources :reviews, only: [:index, :show, :new, :edit] 
  end

  resources :reviews

  resources :restaurants, except: [:new, :create, :edit, :update, :destroy]

  resources :restaurants, only: [:show, :index] do
    resources :reviews, only: [:show, :index]
  end
  get '/reviews/:id/review_data', to: 'reviews#review_data'

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :review_cuisines ,dependent: :destroy
  has_many :cuisines, through: :review_cuisines
  

  before_save { self.restaurant_name = restaurant_name.upcase_first }

  validates_presence_of :restaurant_name, :date_visited, :rating

  validates :content, presence: true, length: { minimum: 10 }

  def restaurant_name
    self.restaurant.name if self.restaurant
  end

  def restaurant_name=(name) 
     self.restaurant = Restaurant.find_or_create_by(name: name)
  end

  def cuisines_attributes=(cuisine_attributes) 
    cuisine_attributes.values.each do |cuisine_attribute| 
      cuisine = Cuisine.find_or_create_by(cuisine_attribute)
      self.cuisines << cuisine
    end
  end

  def self.by_user(user_id) 
    where(user: user_id)
  end

  def self.top_reviews(rating) 
    where(rating: "Excellent")
  end

  def self.order_by_date_visited
    Review.order(date_visited: :desc)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  def index
    @users = User.all.alphabetical_order.page(params[:page]).per(5) 
    if params[:user_id]
      @reviews = User.find(params[:user_id]).reviews.page(params[:page]).per(5)
    elsif params[:restaurant_id]
      @reviews = Restaurant.find(params[:restaurant_id]).reviews.page(params[:page]).per(5)
      render :layout => false
    elsif params[:rating]
      if params[:rating] == "Excellent"
        @reviews = Review.top_reviews(params[:rating]).order_by_date_visited.page(params[:page]).per(5)
      end
    else
      @reviews = Review.all.order_by_date_visited.page(params[:page]).per(5)
    end
  end

  def show
    @current_restaurant ||= Restaurant.find_by(id: @review[:restaurant_id])
    @review.restaurant_id = @current_restaurant.id
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @review}
    end
    
  end

  def review_data
    review = Review.find(params[:id])
    render json: @review
  end

  def new
    @review = Review.new(user_id: params[:user_id])
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      render json: @review, status: 201 
    else
      flash.now[:alert] = "Save Review unsuccesful! Please try again!"
      render 'new'
    end
  end

  def update
    if @review.update(review_params)
      redirect_to @review, notice: "Review updated!"
    else
      flash.now[:alert] = "Review Update unsuccesful! Please try again!"
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to user_path(current_user), notice: "Review deleted!"
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def review_params 
    params.require(:review).permit(:user_id,
                                   :restaurant_name,
                                   :content,
                                   :rating,
                                   :date_visited,
                                   :cuisine_ids => [],
                                   :cuisines_attributes => [:name]
                                   ) 
  end

  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
        <ol style="color:red;font-size:20px;font-style:italic;">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ol>
      </ul>
    </div>
  <% end %>
    
  <br/>
      <%= f.hidden_field :user_id %>
    <div class="field">
      <%= f.label :restaurant_name, "Restaurant Name:" %> &ensp;
      <%= f.text_field :restaurant_name %>
      <br></br>
    </div>
    <div class="field">
      <%= f.text_area :content, placeholder: "Enter Review Comments:", rows: 5, cols: 100 %>
      <br></br> 
    </div>

    <div class="cuisinecheckbox">
      <b>Choose Cuisine: </b>&ensp;
      <%= f.collection_check_boxes :cuisine_ids, Cuisine.all, :id, :name, include_hidden: false %>
    </div>
    <div class="field">
      <b>New Cuisine: </b>&ensp;
      <%= f.fields_for :cuisines, @review.cuisines.build do |cuisine_form| %>
        <%= cuisine_form.text_field :name %>
      <% end %>
      <br></br>
    </div>
    <div class="ratingradiobuttons">
      <b>Restaurant Rating: </b>&ensp;
      <%= f.radio_button :rating, 'Excellent' %>
      <%= f.label :rating, 'Excellent', value: 'Excellent' %>
      <%= f.radio_button :rating, 'Good' %>
      <%= f.label :rating, 'Good', value: 'Good' %>
      <%= f.radio_button :rating, 'Average' %>
      <%= f.label :rating, 'Average', value: 'Average' %>
      <%= f.radio_button :rating, 'Poor' %>
      <%= f.label :rating, 'Poor', value: 'Poor' %>
      <br></br>
    </div>
    <div class="field">
      <%= f.label :date_visited, "Date Visited (or today, #{Time.now.strftime("%m/%d/%Y")}):" %> &ensp;
      <%= f.date_field :date_visited %>
      </br>
    
      <%= f.submit "Save Review", class: "btn btn-outline-primary"%>
      <%= link_to "Back", root_path, class: "btn btn-outline-primary"%>
    </div>
<% end %>

app/views/reviews/_links.html.erb
<% if logged_in? %>
  <%= link_to "User Page", user_path(current_user) %>
  <%= link_to "Create Review", new_review_path %>
  <%= link_to "Top Reviews", reviews_path(rating: "Excellent") %>
<% end %>

app/views/reviews/_more.html.erb
<li>
  <% review.id %><%= link_to review.try(:restaurant).try(:name), review %>
  visited on
  <%= review.date_visited.strftime("%-m/%-d/%Y") %>
  by
  <% if current_user == review.user %>
    <b><%= link_to "you", user_reviews_path(review.user) %></b>
  <% else %>
    <%= link_to review.user.email, user_reviews_path(review.user) %>
  <% end %>&emsp;
  (Posted <%= time_ago_in_words(review.updated_at) %> ago.)
  <div id="body-<%= review.id %>">&emsp;
    Comments:&ensp;"<%= truncate review.content %>"&ensp;
    <a href="javascript:void(0);" class="js-more" data-id="<%= review.id %>">More...</a>&emsp;
  </div>
<br/>
</li>

<script>
  $(function () {
    $(".js-more").on('click', function() {
      var id = $(this).data("id");
      $.get("/reviews/" + id + ".json", function(data) { 
        $("#body-" + id).html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + "Comments: " + '"' + data["content"] + '"');
    
        });
    });
  });
</script>

app/views/reviews/_review.html.erb
<li>
  <%= link_to review.try(:restaurant).try(:name), review %> 
  was visited by
   <% if current_user == review.user %>
    <b>you</b>
  <% else %>
    <b><%= review.user.email %></b>
  <% end %>
  on <%= review.date_visited.strftime("%-m/%-d/%Y") %>.&ensp;
  (Posted <%= time_ago_in_words(review.updated_at) %> ago.)
</li>

app/views/reviews/edit.html.erb
<fieldset>
<legend>
  <h3>
    Edit Your Restaurant Review Below
  </h3>
</legend>
<%= render 'form' %>
</fieldset>
<br/>
<fieldset>
<legend>
  <h3>Delete Review</h3>
</legend>
<br/>

  <%= button_to 'Delete Review', review_path(@review),
              method: :delete,
              data: { confirm: 'This will delete your review PERMANENTLY! Continue?' } ,class: "btn btn-outline-primary"%>
           
  

</fieldset>
<br/>

app/views/reviews/index.html.erb
<br/>
<fieldset>

  <h2>Restaurant Reviews</h2>

<br/>
<ul>
  <% @reviews.each do |review| %>
    <%= render partial: "more", locals: {review: review} %>
  <% end %>
</ul>
<%= page_entries_info @reviews %>
<%= paginate @reviews, window:2 %>
</fieldset>
<br/>

app/views/reviews/new.html.erb
<fieldset>
<legend>
  <h3>Create New Review</h3>
</legend>

<%= render 'form' %>
<div id="reviewResult">
  <h4 id="restaurantName"></h4>
  <p id="reviewBody"></p>
  <p id="reviewCuisines"></p>
  <p id="reviewRating"></p>
  <p id="reviewDateVisited"></p>
  <h4 id="reviewThankYou"></h4>
</div>
<div class="reviewLink"></div>
</fieldset>
<br/>

<script> 
$(function () { 
    $('form').submit(function(event) {   
     
      event.preventDefault();
      var values = $(this).serialize();
      var posting = $.post('/reviews', values); 
      posting.done(function(data) {
        $('#restaurantName').css({ 'font-weight': 'bold' });
        $("#restaurantName").text("Your Review Saved For: " + data["restaurant"]["name"] + '.');
        $("#reviewBody").text("You commented: " + '"' + data["content"] + '".');
        var cuisineType = data["cuisines"][0]["name"];
        $("#reviewCuisines").html("You entered cuisine as: " + '"<b>' + cuisineType + '</b>."');
        
        $.extend({
          showRating: function() {
            var txt1 = data["rating"];
            var txt2 = data["restaurant"]["name"];
            $('#reviewRating').append(`You gave a rating of "<b>${txt1}</b>" for ${txt2}.`);
          }
        });
        $.showRating();
        var visitDate = data["date_visited"];
        var date = new Date(visitDate);
        var newDate = date.toLocaleDateString();
        $("#reviewDateVisited").text("You dined at " + data["restaurant"]["name"] + " on " + newDate + '.');
        var txt1 = "THANK YOU for posting at ";
        var txt2 = $("<b></b>").text("My Restaurant Review!"); 
        $('#reviewThankYou').append(txt1, txt2); 
        $(".reviewLink").html("<a href='/reviews/"+data['id'].toString()+"'>Continue To Review Page</a>");
      });
    });
  });
</script>

app/views/reviews/show.html.erb
<fieldset>

  <h2>Review Page</h2>

<br/>
<ul>
  <li>Restaurant Name:&ensp;
    <span class="restName">
      <b><%= link_to "#{@current_restaurant.name}", restaurant_path(@current_restaurant) %></b>
    </span>
  </li>
  <br/>
  <li>Comments:&ensp;
    <b>"<span class="reviewBody"><%= @review.content %></span>"</b>
  </li>
  <br/>
  <li>Cuisine:&ensp;
    <span class="reviewCuisines">
      <b><%= @review.cuisines.map{|cuisine| cuisine.name}.join(', ').to_s + "." %></b>
    </span>
  </li>
  <br/>
  <li>Rating:&ensp;
  
    <span class="reviewRating">
      <% if @review.rating == "Excellent" %>
        <b><%= link_to "#{@review.rating}", reviews_path(rating: "Excellent") %></b>
      <% elsif @review.rating == "Good" %>
        <b><%= @review.rating %></b>
      <% elsif @review.rating == "Average" %>
        <b><%= @review.rating %></b>
      <% else %>
        <b><%= @review.rating %></b>
      <% end %>
    </span>
    
  </li>
  <br/>
  <li>Date Visited:&ensp;
    <span class="reviewDateVisited">
      <b> <%= @review.date_visited.strftime('%-m/%-d/%Y') %></b>
    </span>
  </li>
  <br/>
  <li>Date Reviewed:&ensp;
    <span class="reviewUpdatedAt">
      <b><%= @review.updated_at.strftime('%-m/%-d/%Y') %></b>
    </span>
  </li>
  <br/>
<% if current_user != @review.user %> 
  <li>Reviewed by:&ensp;
    <span class="userEmail">
      <b><%= @review.user.email %></b>
    </span>
  </li>
  <br/>
<% end %>

</ul>
</fieldset>
<br/>
<fieldset>
<legend>
  <h3>More</h3>
</legend>
<br/>
<% if current_user == @review.user %>
  <li>
    <%= link_to "Edit Review", edit_user_review_path(@review.user, @review) %>
  </li>
<br/>
<% end %>
<li>
  <%= link_to "Load More Reviews", restaurant_reviews_path(@current_restaurant), :class => "load_more_reviews" %>
  for <span class="load_more"><b><%= @current_restaurant.name %></b>.</span>
</li>
<div class="reviews"></div>
</br>
<li>For more info about this restaurant, 'click' to web search for:
  <span class = "search">
    <a target="_blank" href = 'http://www.<%= "#{@review.restaurant_name}" %>.com' data-confirm="Are you sure you want to visit an external website?">
    <%= @review.restaurant_name %></a>
  </span>
</li>
<br/>
  <%= link_to "Back", reviews_path, class: "btn btn-outline-primary"%>
<br/>
</fieldset>
<br/>

<script>
    $(function() {
    $(".load_more_reviews").on("click", function(e) {
    //   $.get( this.href).done(function( response ) {
    //     $(".reviews").html(response)
    //   })
    //   e.preventDefault();

    $.ajax({
        method: "GET",
        url: this.href
      }).done(function(response) {
         $(".reviews").html(response)
      });
      e.preventDefault();
    });
  });
 
</script>