config/routes.rb
Rails.application.routes.draw do
 
  
    root 'users#home'

    resources :users

    get '/signup', to: "users#new"
    post '/signup', to: "users#create"
  
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
  
  
    get '/logout' => 'sessions#destroy'
    

    resources :users, only: [:show] do 
    resources :reviews, only: [:index, :show, :new, :edit] 
  end

  resources :reviews

  resources :restaurants, except: [:new, :create, :edit, :update, :destroy]

  resources :restaurants, only: [:show, :index] do
    resources :reviews, only: [:show, :index]
  end
  get '/reviews/:id/review_data', to: 'reviews#review_data'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-secondary navbar-light">
    <div class="container-fluid">
        
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <%= link_to('Home', root_path, class: "nav-link" ) %>
                </li>
                <li class="nav-item">
                    <%= link_to('Reviews', reviews_path, class: "nav-link" ) %>
                </li>
                <li class="nav-item">
                    <%= link_to('Restaurants', restaurants_path, class: "nav-link" ) %>
                </li>
                <li class="nav-item">
                
                    <% if logged_in? %>
                        <li class="nav-item">   
                            <%= link_to("#{current_user.email.upcase_first}", user_path(current_user), class: "nav-link" ) %>
                        </li>
                        <li class="nav-item">
                            <%= link_to("New Review", new_review_path, class: "nav-link" ) %>
                        </li>
                        <li class="nav-item">
                            <%= link_to("Logout", logout_path, method: :delete, class: "nav-link" ) %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to("Sign Up", signup_path, class: "nav-link" ) %>
                        </li>
                    <% end %>
                    
                </li>
            </ul>
        </div>
    </div>
    <marquee behavior="scroll" direction="left"><h5><i class="bi bi-emoji-heart-eyes"></i>Welcome To My Restaurant Reviews Application!<i class="bi bi-emoji-heart-eyes"></i></h5></marquee>
</nav>


    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant Review App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <%= render 'layouts/header' %>
       
    <div class="container", style="margin-top: 80px;">
     <% flash.each do |name, msg| -%>
                        <strong><%= content_tag :div, msg, class: name %></strong>
                    <% end -%>
      <%= yield %>
    </div>
   
    <div class="footer-basic">
      <footer>
        <ul class="list-inline">
          
          <li class="list-inline-item"><%= render '/users/links' %></li>
          <li class="list-inline-item"><%= render '/reviews/links' %></li>
          <li class="list-inline-item">
            <% if !logged_in? %>
              <%= link_to "Log In", login_path %>
            <% end %>
          </li>
        </ul>
         <p class="copyright"><i class="bi bi-pencil-fill"></i>Author: Chaw Thinzar<i class="bi bi-emoji-sunglasses"></i><br>
           <i class="bi bi-envelope-fill"></i>chawthinzar@cybermissions.co.jp<br>
         <a href="https://www.facebook.com/profile.php?id=100012888365440"><i class="bi bi-facebook"></i>chawthinzar's facebook!</a></p>

      </footer>
    </div>
  </body>
</html>